# SPDX-License-Identifier: MIT
# Copyright (c) 2026 AIDLC Traceability Tool Contributors
"""Parse source code files to extract CODE artifacts."""

from __future__ import annotations

import re
from pathlib import Path

from traceability.models import Artifact, ArtifactType


def parse_code_file(file_path: Path, project_root: Path) -> tuple[Artifact, list[str]]:
    """Parse a source code file and extract traceability hints.

    Returns:
        Tuple of (Artifact, list of hint comments found in the code)
    """
    try:
        content = file_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        content = ""

    # Determine language
    ext = file_path.suffix.lower()
    language_map = {
        ".py": "Python",
        ".js": "JavaScript",
        ".ts": "TypeScript",
        ".tsx": "TypeScript (React)",
        ".jsx": "JavaScript (React)",
    }
    language = language_map.get(ext, "Unknown")

    # Create a simple ID from the file path
    rel_path = file_path.relative_to(project_root)
    artifact_id = f"CODE:{rel_path.as_posix()}"

    # Check if this is a boilerplate file
    is_boilerplate = _is_boilerplate(file_path, content)

    # Extract module/class/function as title
    title = _extract_title(content, file_path, language)
    if is_boilerplate:
        title = f"{title} [Boilerplate]"

    # Look for AIDLC traceability hints in comments
    hints = _extract_traceability_hints(content)

    # Create artifact
    artifact = Artifact(
        id=artifact_id,
        title=title,
        artifact_type=ArtifactType.CODE,
        description=f"Source file: {rel_path.as_posix()}",
        source_file=str(file_path),
        source_line=1,
        metadata={
            "language": language,
            "relative_path": str(rel_path),
            "lines_of_code": len(content.splitlines()),
            "boilerplate": is_boilerplate,
        }
    )

    return artifact, hints


def _is_boilerplate(file_path: Path, content: str) -> bool:
    """Determine if a file is language boilerplate (language-independent).

    Boilerplate files don't contain business logic and shouldn't count against
    traceability coverage metrics. Detects:
    - Package/module initialization files
    - Test infrastructure (fixtures, mocks, factories)
    - Auto-generated code
    - Type definitions and interfaces
    - Constants-only files
    - Example/demo code
    - Version info files
    - Barrel/re-export files
    """
    filename = file_path.name.lower()
    file_path_str = str(file_path).lower()

    # 1. Package/Module initialization (language-specific naming)
    # These are always boilerplate — they are package markers or re-export hubs,
    # not implementation files. The real logic lives in the actual module files.
    init_patterns = {
        "__init__.py",      # Python package init
        "__main__.py",      # Python entry point
        "index.js",         # JavaScript barrel
        "index.ts",         # TypeScript barrel
        "index.jsx",        # React barrel
        "index.tsx",        # React TypeScript barrel
        "package-info.java", # Java package docs
        "module-info.java",  # Java module descriptor (JPMS)
        "assemblyinfo.cs",  # C# assembly info
        "globalusings.cs",  # C# global using directives
        "mod.rs",           # Rust module
        "doc.go",           # Go package documentation
    }
    if filename in init_patterns:
        return True

    # 2. Test infrastructure (by filename pattern)
    test_patterns = [
        "test", "tests", "spec", "specs",      # test files
        "mock", "mocks", "stub", "stubs",      # mocks/stubs
        "fixture", "fixtures",                  # test fixtures
        "factory", "factories",                 # test factories
        "conftest", "testhelper",              # test helpers
    ]
    filename_lower = filename.replace("_", "").replace("-", "")
    for pattern in test_patterns:
        if pattern in filename_lower and "test" in file_path_str:
            return True

    # 3. Test directories (language-independent path detection)
    test_dirs = ["/test/", "/tests/", "/__tests__/", "/spec/", "/specs/",
                 "\\test\\", "\\tests\\", "\\__tests__\\"]
    if any(test_dir in file_path_str for test_dir in test_dirs):
        return True

    # 4. Auto-generated code (by file header)
    first_lines = "\n".join(content.split("\n")[:10]).lower()
    generated_markers = [
        "auto-generated", "autogenerated", "auto generated",
        "generated by", "do not edit", "do not modify",
        "code generator", "automatically generated",
        "this file is generated", "generated file",
    ]
    if any(marker in first_lines for marker in generated_markers):
        return True

    # 5. Type definitions and interfaces (by filename)
    type_patterns = [
        "types", "type", "interface", "interfaces",
        "protocol", "protocols", "contract", "contracts",
    ]
    for pattern in type_patterns:
        if pattern in filename_lower:
            # Check if file is mostly type definitions (few actual implementations)
            lines = [line.strip() for line in content.split("\n") if line.strip()]
            if lines:
                # Look for type/interface/protocol keywords without implementation
                type_def_keywords = ["interface ", "protocol ", "type ", "typedef ",
                                    "enum ", "struct ", "class ", "abstract "]
                type_lines = sum(1 for line in lines if any(kw in line.lower() for kw in type_def_keywords))
                if type_lines / len(lines) > 0.5:  # >50% type definitions
                    return True

    # 6. Constants-only files (by filename and content)
    const_patterns = ["constant", "constants", "config", "settings", "enums", "enum"]
    if any(pattern in filename_lower for pattern in const_patterns):
        # Check if mostly constant assignments, no functions/methods
        lines = [line.strip() for line in content.split("\n") if line.strip()]
        if lines:
            # Count assignment statements vs function/method definitions
            assignment_keywords = ["=", "const ", "final ", "static final", "readonly "]
            function_keywords = ["def ", "function ", "func ", "fn ", "void ",
                               "public ", "private ", "protected "]
            assignments = sum(1 for line in lines if any(kw in line for kw in assignment_keywords))
            functions = sum(1 for line in lines if any(kw in line.lower() for kw in function_keywords))
            if assignments > 5 and functions == 0 and assignments / len(lines) > 0.4:
                return True

    # 7. Example/demo code (by path or filename)
    example_patterns = ["example", "demo", "sample", "tutorial"]
    if any(pattern in filename_lower or pattern in file_path_str for pattern in example_patterns):
        return True

    # 8. Version/build info files
    version_patterns = ["version", "__version__", "buildinfo", "build_info", "versioninfo"]
    if any(pattern in filename_lower for pattern in version_patterns):
        # If small file (<15 lines), it's likely just version strings
        if len([line for line in content.split("\n") if line.strip()]) < 15:
            return True

    # 9. Barrel/re-export files (language-independent)
    # Files that are mostly imports/exports
    lines = [line.strip() for line in content.split("\n") if line.strip()]
    if len(lines) > 3:
        export_import_keywords = ["import ", "export ", "from ", "require(",
                                 "include ", "#include", "use ", "using "]
        export_import_lines = sum(1 for line in lines
                                 if any(line.startswith(kw) for kw in export_import_keywords))
        if export_import_lines / len(lines) > 0.75:  # >75% imports/exports
            return True

    # 10. Generated/migration directories
    generated_dirs = ["/generated/", "/gen/", "/.generated/",
                     "/migrations/", "/migrate/", "/db/migrate/",
                     "\\generated\\", "\\gen\\", "\\migrations\\"]
    if any(gen_dir in file_path_str for gen_dir in generated_dirs):
        return True

    return False


def _extract_title(content: str, file_path: Path, language: str) -> str:
    """Extract a meaningful title from the source code."""
    lines = content.split("\n")

    # Look for module docstring or first class/function
    if language == "Python":
        # Try to find module docstring
        for i, line in enumerate(lines[:20]):
            if i == 0 and (line.startswith('"""') or line.startswith("'''")):
                # Multi-line docstring
                docstring_lines = [line.strip('"\' ')]
                for j in range(i + 1, min(i + 10, len(lines))):
                    if '"""' in lines[j] or "'''" in lines[j]:
                        docstring_lines.append(lines[j].split('"""')[0].split("'''")[0].strip())
                        break
                    docstring_lines.append(lines[j].strip())
                title = " ".join(docstring_lines).strip()
                if title and len(title) < 100:
                    return title

        # Look for class or function definition
        for line in lines[:50]:
            if line.startswith("class "):
                match = re.match(r"class\s+(\w+)", line)
                if match:
                    return f"Class: {match.group(1)}"
            elif line.startswith("def ") and not line.startswith("def _"):
                match = re.match(r"def\s+(\w+)", line)
                if match:
                    return f"Function: {match.group(1)}"

    elif language in ["JavaScript", "TypeScript", "JavaScript (React)", "TypeScript (React)"]:
        # Look for export class/function
        for line in lines[:50]:
            if "export class" in line or "class " in line:
                match = re.search(r"class\s+(\w+)", line)
                if match:
                    return f"Class: {match.group(1)}"
            elif "export function" in line or "export const" in line:
                match = re.search(r"(?:function|const)\s+(\w+)", line)
                if match:
                    return f"Function: {match.group(1)}"

    # Fallback: use filename
    return file_path.stem.replace("_", " ").replace("-", " ").title()


def _extract_traceability_hints(content: str) -> list[str]:
    """Extract AIDLC traceability hints from code comments.

    Looks for patterns like:
    # AIDLC-Unit: foundation-config
    # AIDLC-Story: US-2.1, US-2.2
    # AIDLC-Requirement: FR-1
    // AIDLC-Unit: validation-discovery
    """
    hints = []

    # Pattern: # AIDLC-XXX: value or // AIDLC-XXX: value
    pattern = re.compile(r"(?:#|//)\s*AIDLC-(\w+):\s*(.+)", re.IGNORECASE)

    for line in content.split("\n"):
        match = pattern.search(line)
        if match:
            hint_type = match.group(1).lower()
            hint_value = match.group(2).strip()
            hints.append(f"{hint_type}:{hint_value}")

    return hints


def parse_all_code_files(code_files: list[Path], project_root: Path) -> list[Artifact]:
    """Parse all source code files and return CODE artifacts."""
    artifacts = []

    for code_file in code_files:
        artifact, hints = parse_code_file(code_file, project_root)

        # Store hints in metadata for later AI processing
        if hints:
            artifact.metadata["traceability_hints"] = hints

        artifacts.append(artifact)

    return artifacts
